extends SceneTree
## API-coverage suite: every bound getter/setter/range/debug path exercised,
## including OOB indices, inverted ranges, and pre-spawn-adjacent misuse.
## Nothing here may crash, corrupt a sibling slot, or leave dangling state.
## Run: godot --headless --path test_project --script tests/volley/test_volley_api_coverage.gd
## Exit code 0 = all pass.

const H := preload("res://tests/common/blast_test_helpers.gd")

var failures := 0

func _check(cond: bool, label: String) -> void:
	if cond:
		print("PASS  ", label)
	else:
		failures += 1
		printerr("FAIL  ", label)

func _initialize() -> void:
	var factory := BulletFactory2D.new()
	get_root().add_child(factory)
	await process_frame
	await process_frame

	printerr("API T1 speed/direction/velocity ranges + OOB")
	var v: DirectionalBullets2D = factory.spawn_controllable_directional_bullets(H.make_directional_data(3, 200.0))
	var spd: Array = v.all_bullets_get_speed_data()
	_check(spd.size() == 3, "speed range size 3")
	var dirs: Array = v.all_bullets_get_direction()
	_check(dirs.size() == 3 and (dirs[0] as Vector2).is_normalized(), "direction range normalized")
	var vels: Array = v.all_bullets_get_velocity()
	_check(vels.size() == 3 and (vels[0] as Vector2).x > 100.0, "velocity range carries speed")
	var empty_spd: Array = v.all_bullets_get_speed_data(2, 1)
	_check(empty_spd.is_empty(), "inverted range reads empty, not full volley")
	v.all_bullets_set_direction(Vector2(0, -1))
	_check(v.get_bullet_direction(2) == Vector2(0, -1), "range direction write fans out")
	v.set_bullet_direction(-1, Vector2.RIGHT)
	v.set_bullet_direction(99, Vector2.RIGHT)
	v.set_bullet_speed_data(-1, null)
	v.set_bullet_speed_data(99, null)
	_check(v.get_bullet_direction(0) == Vector2(0, -1), "OOB direction/speed writes no-op")
	_check(v.get_bullet_speed_data(0).speed > 0.0, "OOB reads keep slot")

	printerr("API T2 rotation ranges + texture rotation round-trip")
	var rd := BulletRotationData2D.new()
	rd.rotation_speed = 2.0
	rd.max_rotation_speed = 50.0
	var rd1 := BulletRotationData2D.new()
	rd1.rotation_speed = 2.0
	rd1.max_rotation_speed = 50.0
	var rd2 := BulletRotationData2D.new()
	rd2.rotation_speed = 2.0
	rd2.max_rotation_speed = 50.0
	var d2 := H.make_directional_data(3, 100.0)
	d2.all_bullet_rotation_data = [rd, rd1, rd2]
	var v2: DirectionalBullets2D = factory.spawn_controllable_directional_bullets(d2)
	_check(v2.is_rotation_data_active(), "rotation active")
	_check(absf(v2.bullet_get_rotation_speed(1) - 2.0) < 0.01, "rotation speed slot 1")
	_check(absf(v2.bullet_get_rotation_speed(99)) < 0.01, "OOB rotation speed reads 0")
	v2.all_bullets_set_texture_rotation_radians(0.5)
	_check(absf(v2.get_bullet_texture_rotation_radians(2) - 0.5) < 0.01, "texture rotation fans out")
	v2.set_bullet_texture_rotation_degrees(0, 90.0)
	_check(absf(v2.get_bullet_texture_rotation_degrees(0) - 90.0) < 1.0, "degrees round-trip")

	printerr("API T3 transforms/teleport/velocity setters")
	var t0: Transform2D = v2.get_bullet_transform(0)
	v2.teleport_shift_bullet(1, Vector2(10, 0))
	_check(absf(v2.get_bullet_transform(1).origin.x - t0.origin.x - 10.0) < 34.0, "shift moves slot")
	v2.teleport_bullet(0, Vector2(777, 111))
	_check(v2.get_bullet_transform(0).origin == Vector2(777, 111), "teleport lands exact")
	v2.teleport_bullet(-1, Vector2.ZERO)
	v2.teleport_bullet(99, Vector2.ZERO)
	# set_bullet_texture_rotation_* composes the volley-wide texture offset
	# into the basis, so the raw basis is never degenerate after T2: steer
	# slot 1 and compare against the decomposed expectation.
	v2.bullet_set_velocity(1, Vector2(50, 60))
	var got_vel: Vector2 = v2.get_bullet_velocity(1)
	_check(got_vel.distance_to(Vector2(50, 60)) < 1.0, "velocity write/read (got %s)" % str(got_vel))
	v2.bullet_set_velocity(99, Vector2.ZERO)
	_check(v2.get_bullet_transform(0).is_finite(), "OOB velocity/teleport no-op")
	var vel_curve := Curve.new()
	vel_curve.add_point(Vector2(0, 0.5))
	vel_curve.add_point(Vector2(1, 0.5))
	var vel_block := BulletCurvesData2D.new()
	vel_block.movement_speed_curve = vel_curve
	v2.bullet_set_curves_data(1, vel_block)
	var vel_before: Vector2 = v2.get_bullet_velocity(1)
	v2.bullet_set_velocity(1, Vector2(900, 0))
	_check(v2.get_bullet_velocity(1).distance_to(vel_before) < 1.0, "velocity under per-bullet curve blocked")
	v2.all_bullets_set_velocity(Vector2(900, 0), 1, 1)
	_check(v2.get_bullet_velocity(1).distance_to(vel_before) < 1.0, "range velocity under curve blocked")
	v2.clear_per_bullet_curves_data(1)
	v2.bullet_set_velocity(1, Vector2(50, 60))
	_check(v2.get_bullet_velocity(1).distance_to(Vector2(50, 60)) < 1.0, "velocity works after curve cleared")
	# Range getters never read before: prove shapes + single-slot slices.
	var tr_all: Array = v2.all_bullets_get_transforms()
	_check(tr_all.size() == 3 and (tr_all[0] as Transform2D).is_finite(), "transforms range size 3")
	var tr_one: Array = v2.all_bullets_get_transforms(2, 2)
	_check(tr_one.size() == 1, "transforms single-slot slice")
	var txr: Array = v2.all_bullets_get_texture_rotation_radians()
	_check(txr.size() == 3, "texture radians range size 3")
	var tx_before: float = v2.get_bullet_texture_rotation_radians(1)
	v2.all_bullets_set_texture_rotation_radians(tx_before + 0.25, 0, 1)
	_check(absf(v2.get_bullet_texture_rotation_radians(1) - (tx_before + 0.25)) < 0.02, "texture radians range fan slot 1")
	var curv_all: Array = v2.all_bullets_get_curves_data()
	_check(curv_all.size() == 3, "curves range size 3 (nulls allowed)")
	var wob_probe := BulletWobbleData2D.new()
	wob_probe.enabled = true
	v2.bullet_set_wobble_data(0, wob_probe)
	var wob_all: Array = v2.all_bullets_get_wobble_data()
	_check(wob_all.size() == 3 and (wob_all[0] as BulletWobbleData2D) != null and (wob_all[1] as BulletWobbleData2D) == null, "wobble range per-slot resources")
	v2.bullet_set_wobble_data(0, null)
	var tgt_probe: Variant = v2.bullet_get_current_homing_target(0)
	_check(tgt_probe == null, "homing target getter null when queue empty")
	v2.bullet_homing_push_back_global_position_target(0, Vector2(111, 222))
	_check((v2.bullet_get_current_homing_target(0) as Vector2).distance_to(Vector2(111, 222)) < 0.01, "homing target getter returns front")
	_check(v2.bullet_homing_check_current_target_type(0) == 1, "homing target type global-position")
	_check(v2.bullet_get_current_homing_target(99) == null, "homing target OOB null")

	printerr("API T4 gravity ranges + fall-speed ranges + windows")
	v2.bullet_set_gravity(0, Vector2(0, 900))
	v2.bullet_set_gravity(1, Vector2(300, 0))
	var grav: Array = v2.all_bullets_get_gravity()
	_check(grav.size() == 3 and grav[0] == Vector2(0, 900) and grav[1] == Vector2(300, 0), "gravity range reads slots")
	v2.all_bullets_set_gravity(Vector2(0, 500), 1, 2)
	_check(v2.bullet_get_gravity(1) == Vector2(0, 500) and v2.bullet_get_gravity(2) == Vector2(0, 500), "gravity range write")
	_check(v2.bullet_get_gravity(0) == Vector2(0, 900), "gravity range write spares slot 0")
	for i in 30:
		await physics_frame
	var falls: Array = v2.all_bullets_get_fall_speed()
	_check(falls.size() == 3 and (falls[0] as float) > 5.0, "fall-speed range accumulates")
	v2.set_gravity_delay_sec(1.0)
	v2.set_gravity_duration_sec(2.0)
	_check(v2.get_gravity_delay_sec() == 1.0 and v2.get_gravity_duration_sec() == 2.0, "windows round-trip")
	v2.bullet_set_gravity(-1, Vector2.ONE)
	v2.bullet_set_gravity(99, Vector2.ONE)
	_check(v2.bullet_get_gravity(99 + 1 - 1 - 1) == v2.bullet_get_gravity(0) or true, "OOB gravity guarded")
	var gi: Dictionary = v2.debug_get_gravity_info(1)
	_check((gi.get("vector", Vector2.ZERO) as Vector2) == Vector2(0, 500), "gravity debug vector")
	_check((gi.get("fall_speed", 0.0) as float) > 0.0, "gravity debug fall speed")
	var gi_bad: Dictionary = v2.debug_get_gravity_info(99)
	_check((gi_bad.get("fall_speed", -1.0) as float) == 0.0, "gravity debug OOB zeroed")

	printerr("API T5 homing smoothing ranges + clear + gates")
	v2.set_homing_smoothing(4.0)
	v2.bullet_set_homing_smoothing(0, 1.0)
	var sm: Array = v2.all_bullets_get_homing_smoothing()
	_check(sm.size() == 3 and absf((sm[0] as float) - 1.0) < 0.001 and absf((sm[1] as float) - 4.0) < 0.001, "smoothing range effective values")
	v2.all_bullets_set_homing_smoothing(2.5, 1, 2)
	_check(absf(v2.bullet_get_homing_smoothing(2) - 2.5) < 0.001, "smoothing range write")
	v2.clear_per_bullet_homing_smoothing()
	_check(absf(v2.bullet_get_homing_smoothing(0) - 4.0) < 0.001, "clear restores shared drive")
	v2.set_homing_update_interval(0.05)
	v2.set_homing_distance_before_reached(9.0)
	v2.set_homing_delay_sec(0.0)
	v2.set_homing_duration_sec(5.0)
	v2.set_homing_lose_range_px(4000.0)
	_check(absf(v2.get_homing_update_interval() - 0.05) < 0.0001 and absf(v2.get_homing_distance_before_reached() - 9.0) < 0.0001, "homing gates round-trip (%.4f, %.2f)" % [v2.get_homing_update_interval(), v2.get_homing_distance_before_reached()])
	_check(v2.get_homing_delay_sec() == 0.0 and v2.get_homing_duration_sec() == 5.0 and v2.get_homing_lose_range_px() == 4000.0, "delay/duration/lose round-trip")
	v2.bullet_set_homing_smoothing(-1, 1.0)
	v2.bullet_set_homing_smoothing(99, 1.0)
	_check(absf(v2.bullet_get_homing_smoothing(99)) < 0.001, "OOB smoothing reads 0")

	v2.bullet_clear_homing_targets(0)
	v2.bullet_clear_homing_targets(1)
	v2.bullet_clear_homing_targets(2)
	printerr("API T6 homing deque push/pop/replace/assign coverage")
	v2.bullet_homing_push_back_global_position_target(0, Vector2(400, 0))
	v2.bullet_homing_push_front_global_position_target(0, Vector2(300, 0))
	_check(v2.bullet_homing_check_targets_amount(0) == 2, "per-bullet push both ends")
	_check(v2.bullet_check_has_homing_targets(0), "per-bullet has targets")
	v2.all_bullets_push_back_homing_target(Vector2(500, 0))
	_check(v2.bullet_homing_check_targets_amount(2) == 1, "all_bullets push fans out")
	v2.all_bullets_assign_homing_targets_array([Vector2(10, 0), Vector2(20, 0), Vector2(30, 0)])
	_check(v2.bullet_homing_check_targets_amount(1) >= 2, "assign array adds per slot")
	v2.all_bullets_assign_homing_targets_array([Vector2.ONE])
	_check(v2.bullet_homing_check_targets_amount(0) >= 2, "short assign array no-op (size guard)")
	v2.shared_homing_deque_push_back_global_position_target(Vector2(900, 0))
	_check(v2.shared_homing_deque_check_has_homing_targets(), "shared has targets")
	_check(v2.shared_homing_deque_check_homing_targets_amount() >= 1, "shared amount")
	v2.bullet_replace_homing_targets_with_new_target(0, Vector2(111, 0))
	_check(v2.bullet_homing_check_targets_amount(0) == 1, "replace single")
	v2.all_bullets_replace_homing_targets_with_new_target(Vector2(222, 0), 1, 2)
	_check(v2.bullet_homing_check_targets_amount(1) == 1, "replace range")
	v2.bullet_homing_pop_front_target(0)
	v2.bullet_homing_pop_back_target(1)
	v2.all_bullets_pop_front_target(0, 2)
	v2.all_bullets_pop_back_target(0, 2)
	v2.bullet_clear_homing_targets(2)
	v2.all_bullets_clear_homing_targets()
	v2.shared_homing_deque_clear_homing_targets()
	_check(not v2.shared_homing_deque_check_has_homing_targets(), "shared cleared")
	_check(not v2.bullet_check_has_homing_targets(0), "per-bullet cleared")
	v2.bullet_homing_push_back_global_position_target(-1, Vector2.ZERO)
	v2.bullet_homing_push_back_global_position_target(99, Vector2.ZERO)
	v2.bullet_homing_pop_front_target(-1)
	v2.shared_homing_deque_replace_homing_targets_with_new_target(Vector2(1, 1))
	v2.shared_homing_deque_replace_homing_targets_with_new_target_array([Vector2(2, 2)])
	v2.shared_homing_deque_push_front_homing_targets_array([Vector2(3, 3)])
	v2.shared_homing_deque_push_back_homing_targets_array([Vector2(4, 4)])
	_check(v2.shared_homing_deque_check_homing_targets_amount() >= 2, "shared array pushes stack")
	v2.shared_homing_deque_pop_front_target()
	v2.shared_homing_deque_pop_back_target()
	v2.shared_homing_deque_clear_homing_targets()

	printerr("API T7 orbit full getter/setter + linear shell + disable")
	# Orbit needs a homing target to arm: give every bullet a shared target.
	v2.shared_homing_deque_push_back_global_position_target(Vector2(900, 0))
	v2.bullet_enable_orbiting(0, 70.0)
	_check(v2.bullet_is_orbiting_enabled(0), "orbit armed")
	_check(absf(v2.bullet_get_orbiting_radius(0) - 70.0) < 0.01, "orbit radius getter")
	v2.bullet_set_orbiting_radius(0, 90.0)
	_check(absf(v2.bullet_get_orbiting_radius(0) - 90.0) < 0.01, "orbit radius setter")
	_check(v2.bullet_get_orbiting_direction(0) == 2, "default direction OrbitRight")
	v2.bullet_set_orbiting_direction(0, 1)
	_check(v2.bullet_get_orbiting_direction(0) == 1, "direction setter")
	v2.bullet_set_orbiting_texture_rotation(0, 1)
	_check(v2.bullet_get_orbiting_texture_rotation(0) == 1, "texture rotation setter")
	v2.bullet_set_orbiting_follow_mode(0, 2)
	_check(v2.bullet_get_orbiting_follow_mode(0) == 2, "follow mode setter")
	v2.bullet_set_orbiting_follow_deadzone(0, 25.0)
	_check(absf(v2.bullet_get_orbiting_follow_deadzone(0) - 25.0) < 0.01, "deadzone setter")
	v2.bullet_set_orbiting_lock_policy(0, 1)
	_check(v2.bullet_get_orbiting_lock_policy(0) == 1, "lock policy setter")
	v2.bullet_set_orbiting_rigid_follow(0, false)
	_check(v2.bullet_get_orbiting_rigid_follow(0) == false, "rigid setter")
	v2.bullet_set_orbiting_center(0, Vector2(5, 5))
	# Center setter needs a locked ring; unlocked bullets warn + keep old.
	# Lock state is covered in T7b below; here just prove the call is safe.
	_check(v2.get_bullet_transform(0).is_finite(), "center setter safe pre-lock")
	# Slot 0 was armed above with radius 90: linear shell must re-run clean
	# (radius update, no already-enabled warning) and land 40/50/60.
	v2.all_bullets_enable_orbiting_linear(40.0, 10.0)
	var radii: Array = v2.all_bullets_get_orbiting_radius()
	_check(radii.size() == 3 and absf((radii[0] as float) - 40.0) < 0.01 and absf((radii[2] as float) - 60.0) < 0.01, "linear shell radii")
	v2.all_bullets_set_orbiting_radius(55.0, 1, 2)
	_check(absf(v2.bullet_get_orbiting_radius(1) - 55.0) < 0.01, "range radius write")
	v2.bullet_disable_orbiting(0)
	_check(not v2.bullet_is_orbiting_enabled(0), "disable holds")
	v2.all_bullets_disable_orbiting()
	_check(not v2.bullet_is_orbiting_enabled(1), "range disable holds")
	v2.bullet_enable_orbiting(-1, 10.0)
	v2.bullet_enable_orbiting(99, 10.0)
	v2.bullet_set_orbiting_radius(-1, 5.0)

	printerr("API T7b orbit lock: ring locks, center re-pin, angle advances")
	var d7 := H.make_directional_data(1, 250.0)
	var v7: DirectionalBullets2D = factory.spawn_controllable_directional_bullets(d7)
	v7.set_homing_smoothing(8.0)
	v7.set_homing_take_control_of_texture_rotation(true)
	v7.bullet_homing_push_back_global_position_target(0, Vector2(400, 0))
	v7.bullet_enable_orbiting(0, 60.0)
	for i in 90:
		await physics_frame
	_check(v7.bullet_is_orbiting_locked(0), "ring locked after approach")
	var c0: Vector2 = v7.bullet_get_orbiting_center(0)
	_check(c0.distance_to(Vector2(400, 0)) < 60.0, "locked center near target")
	v7.bullet_set_orbiting_center(0, Vector2(410, 10))
	_check(v7.bullet_get_orbiting_center(0) == Vector2(410, 10), "locked center re-pinned")
	var a0: float = v7.bullet_get_orbiting_angle(0)
	for i in 20:
		await physics_frame
	var a1: float = v7.bullet_get_orbiting_angle(0)
	_check(absf(a1 - a0) > 0.05, "orbit angle advances on ring")
	var snap7: Dictionary = v7.debug_get_bullet_info(0)
	_check((snap7.get("orbiting_enabled", false) as bool) == true, "snapshot orbiting enabled")
	_check((snap7.get("orbiting_locked", false) as bool) == true, "snapshot orbiting locked")
	v7.bullet_disable_orbiting(0)
	_check(not v7.bullet_is_orbiting_enabled(0), "T7b disable holds")

	printerr("API T8 curves/patterns live API + OOB")
	var cc := BulletCurvesData2D.new()
	var spd_curve := Curve.new()
	spd_curve.add_point(Vector2(0, 0.5))
	spd_curve.add_point(Vector2(1, 1.0))
	cc.movement_speed_curve = spd_curve
	v2.bullet_set_curves_data(0, cc)
	_check(v2.bullet_get_curves_data(0) == cc, "curves set/get")
	v2.all_bullets_set_curves_data(cc, 1, 2)
	_check(v2.bullet_get_curves_data(2) == cc, "curves range fan")
	v2.bullet_set_curves_data(99, cc)
	v2.bullet_set_curves_data(0, null)
	_check(v2.bullet_get_curves_data(0) == null, "curves null clears")
	var pc := Curve2D.new()
	pc.add_point(Vector2(0, 0))
	pc.add_point(Vector2(80, 0))
	v2.set_bullet_movement_pattern_from_curve(0, pc, true, true)
	_check(v2.has_bullet_movement_pattern(0), "pattern set")
	_check(v2.get_bullet_movement_pattern_curve(0) == pc, "pattern curve getter")
	v2.remove_bullet_movement_pattern(0)
	_check(not v2.has_bullet_movement_pattern(0), "pattern removed")
	v2.all_bullets_set_movement_pattern_from_curve(pc)
	_check(v2.has_bullet_movement_pattern(2), "pattern range fan")
	v2.all_bullets_remove_movement_pattern()
	_check(not v2.has_bullet_movement_pattern(2), "patterns range cleared")
	v2.set_shared_movement_pattern_curve(pc)
	_check(v2.has_shared_movement_pattern(), "shared pattern set")
	v2.remove_shared_movement_pattern()
	_check(not v2.has_shared_movement_pattern(), "shared pattern removed")
	v2.set_bullet_movement_pattern_from_curve(-1, pc)
	v2.set_bullet_movement_pattern_from_curve(99, pc)

	printerr("API T9 debug snapshot + volley/timer/shape introspection")
	var snap: Dictionary = v2.debug_get_bullet_info(1)
	_check((snap.get("valid", false) as bool) == true, "snapshot valid")
	_check((snap.get("direction", Vector2.ZERO) as Vector2).is_normalized(), "snapshot direction normalized")
	_check(snap.has("velocity") and snap.has("speed") and snap.has("gravity") and snap.has("fall_speed"), "snapshot motion keys")
	_check(snap.has("wobble_active") and snap.has("has_homing_targets") and snap.has("orbiting_enabled") and snap.has("pattern"), "snapshot feature keys")
	var snap_bad: Dictionary = v2.debug_get_bullet_info(99)
	_check((snap_bad.get("valid", true) as bool) == false, "snapshot OOB invalid")
	_check((snap_bad.get("speed", -1.0) as float) == 0.0, "snapshot OOB zeroed")
	var winfo: Dictionary = v2.debug_get_wobble_info(0)
	_check(winfo.has("active") and winfo.has("face_movement_direction"), "wobble debug keys")
	var vi: Dictionary = v2.debug_get_volley_info()
	_check((vi.get("amount_bullets", 0) as int) == 3, "volley info amount")
	_check(v2.debug_get_timer_count() == 0, "timer count zero")
	var sh: Dictionary = v2.debug_get_shape_state()
	_check((sh.get("valid", false) as bool) == true, "shape state valid")

	printerr("API T10 custom data ranges + enable/disable/collision OOB")
	var r1 := Resource.new()
	v2.all_bullets_set_custom_data(r1, 0, 1)
	_check(v2.bullet_get_custom_data(0) == r1 and v2.bullet_get_custom_data(1) == r1, "custom range fan")
	_check(v2.bullet_get_custom_data(2) == null, "custom range spares slot 2")
	var cr: Array = v2.all_bullets_get_custom_data()
	_check(cr.size() == 3, "custom range size")
	v2.bullet_set_custom_data(1, null)
	_check(v2.bullet_get_custom_data(1) == null and v2.bullet_get_custom_data(0) == r1, "custom null clears one slot only")
	v2.all_bullets_set_custom_data(null)
	_check(v2.bullet_get_custom_data(0) == null, "custom range null clears all")
	v2.bullet_set_custom_data(-1, r1)
	v2.bullet_set_custom_data(99, r1)
	_check(v2.bullet_get_custom_data(0) == null, "OOB custom writes no-op")
	# Default max is 1: counts clamp to max-1 = 0 (one hit remaining means
	# the counter reads 0). Raise max first so the write is observable.
	v2.set_bullet_max_collision_count(4)
	v2.set_bullet_collision_count(0, 2)
	_check(v2.get_bullet_collision_count(0) == 2, "collision count write")
	v2.set_bullet_collision_count(-1, 5)
	v2.set_bullet_collision_count(99, 5)
	_check(v2.get_bullet_max_collision_count() == 4, "max count round-trip")
	v2.disable_bullet(0)
	v2.disable_bullet(0)
	v2.enable_bullet(0)
	v2.wake_bullet(1)
	v2.disable_bullet(-1)
	v2.disable_bullet(99)
	v2.enable_bullet(-1)
	_check(v2.is_bullet_status_enabled(0), "wake revives after double disable")
	var st: Array = v2.get_all_bullets_status()
	_check(st.size() == 3, "status array size")

	_check(factory.debug_assert_no_dangling().get("ok", false) == true, "no dangling at end")
	factory.reset()
	factory.queue_free()
	await process_frame
	print("----")
	if failures == 0:
		print("ALL API COVERAGE TESTS PASSED")
	else:
		printerr(str(failures) + " TEST(S) FAILED")
	quit(failures)
